# Generated by Django 4.2.1 on 2023-05-31 08:21

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_task_options_rename_create_task_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=base.models.one_week_hence),
        ),
    ]
